version: '3.8'

services:
  phpliteadmin:
    image:  acttaiwan/phpliteadmin
    container_name: phpliteadmin
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./dbase.db:/var/www/html/dbase.db
    environment:
      - SQLITE_DATABASE=dbase.db