version: '3.8'

services:
  
  phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST:  db
      PMA_PORT:  3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data: 

networks:
  app_network: 
    driver: bridge